numbers = [1,2,3]
print(numbers)
numbers[1] = 17
print(numbers)
numbers.extend([4,5,6])
print(numbers)
numbers.pop()
print(numbers)
numbers.pop(0)
print(numbers)
numbers.append(6)
print(numbers)
sorted(numbers)
print(numbers)
numbers.sort()
print(numbers)
numbers.sort(reverse=True)
print(numbers)
numbers.insert(3,25)
print(numbers)
